# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ReplaceItemInExcelDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 361, 253))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.m_v_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.m_v_layout.setContentsMargins(0, 0, 0, 0)
        self.m_v_layout.setObjectName("m_v_layout")
        self.label1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label1.setObjectName("label1")
        self.m_v_layout.addWidget(self.label1)
        self.h_layout = QtWidgets.QHBoxLayout()
        self.h_layout.setContentsMargins(3, 3, 3, 3)
        self.h_layout.setObjectName("h_layout")
        self.projectTableWidget = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        self.projectTableWidget.setObjectName("projectTableWidget")
        self.projectTableWidget.setColumnCount(0)
        self.projectTableWidget.setRowCount(0)
        self.h_layout.addWidget(self.projectTableWidget)
        self.v_layout = QtWidgets.QVBoxLayout()
        self.v_layout.setContentsMargins(3, 3, 3, 3)
        self.v_layout.setObjectName("v_layout")
        self.insertButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.insertButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.insertButton.setObjectName("insertButton")
        self.v_layout.addWidget(self.insertButton)
        self.removeButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.removeButton.setObjectName("removeButton")
        self.v_layout.addWidget(self.removeButton)
        self.h_layout.addLayout(self.v_layout)
        self.m_v_layout.addLayout(self.h_layout)
        self.b_h_layout = QtWidgets.QHBoxLayout()
        self.b_h_layout.setContentsMargins(3, 3, 3, 3)
        self.b_h_layout.setObjectName("b_h_layout")
        self.searchButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.searchButton.setObjectName("searchButton")
        self.b_h_layout.addWidget(self.searchButton)
        self.closeButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.closeButton.setObjectName("closeButton")
        self.b_h_layout.addWidget(self.closeButton)
        self.m_v_layout.addLayout(self.b_h_layout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "替换清单项目"))
        self.label1.setText(_translate("Dialog", "列对应表"))
        self.insertButton.setText(_translate("Dialog", "+"))
        self.removeButton.setText(_translate("Dialog", "-"))
        self.searchButton.setText(_translate("Dialog", "搜索"))
        self.closeButton.setText(_translate("Dialog", "关闭"))
