# -*- coding: utf-8 -*-

# Form implementation generated from reading CreatePartDialog.ui file 'ProductMainWindow.CreatePartDialog.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(722, 606)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMaximumSize(QtCore.QSize(716, 16777215))
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 722, 26))
        self.menubar.setObjectName("menubar")
        self.productTopMenu = QtWidgets.QMenu(self.menubar)
        self.productTopMenu.setObjectName("productTopMenu")
        self.customerTopMenu = QtWidgets.QMenu(self.menubar)
        self.customerTopMenu.setObjectName("customerTopMenu")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.toolsTopMenu = QtWidgets.QMenu(self.menubar)
        self.toolsTopMenu.setObjectName("toolsTopMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.exitAction = QtWidgets.QAction(MainWindow)
        self.exitAction.setObjectName("exitAction")
        self.addProductAction = QtWidgets.QAction(MainWindow)
        self.addProductAction.setObjectName("addProductAction")
        self.addServiceRecordAction = QtWidgets.QAction(MainWindow)
        self.addServiceRecordAction.setObjectName("addServiceRecordAction")
        self.addCustomerAction = QtWidgets.QAction(MainWindow)
        self.addCustomerAction.setObjectName("addCustomerAction")
        self.addSaleContractAction = QtWidgets.QAction(MainWindow)
        self.addSaleContractAction.setObjectName("addSaleContractAction")
        self.editCustomerAction = QtWidgets.QAction(MainWindow)
        self.editCustomerAction.setObjectName("editCustomerAction")
        self.editSaleContractAction = QtWidgets.QAction(MainWindow)
        self.editSaleContractAction.setObjectName("editSaleContractAction")
        self.getAvailableSerNrAction = QtWidgets.QAction(MainWindow)
        self.getAvailableSerNrAction.setObjectName("getAvailableSerNrAction")
        self.actionAdd2Contract = QtWidgets.QAction(MainWindow)
        self.actionAdd2Contract.setVisible(False)
        self.actionAdd2Contract.setObjectName("actionAdd2Contract")
        self.productTopMenu.addAction(self.addProductAction)
        self.productTopMenu.addAction(self.addServiceRecordAction)
        self.productTopMenu.addSeparator()
        self.productTopMenu.addAction(self.actionAdd2Contract)
        self.customerTopMenu.addAction(self.addCustomerAction)
        self.customerTopMenu.addAction(self.addSaleContractAction)
        self.customerTopMenu.addAction(self.editCustomerAction)
        self.customerTopMenu.addAction(self.editSaleContractAction)
        self.menu.addAction(self.exitAction)
        self.toolsTopMenu.addAction(self.getAvailableSerNrAction)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.productTopMenu.menuAction())
        self.menubar.addAction(self.customerTopMenu.menuAction())
        self.menubar.addAction(self.toolsTopMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "产品管理"))
        self.productTopMenu.setTitle(_translate("MainWindow", "产品"))
        self.customerTopMenu.setTitle(_translate("MainWindow", "客户"))
        self.menu.setTitle(_translate("MainWindow", "全局"))
        self.toolsTopMenu.setTitle(_translate("MainWindow", "工具"))
        self.exitAction.setText(_translate("MainWindow", "退出"))
        self.exitAction.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.addProductAction.setText(_translate("MainWindow", "添加产品"))
        self.addServiceRecordAction.setText(_translate("MainWindow", "添加售后记录"))
        self.addCustomerAction.setText(_translate("MainWindow", "新建客户"))
        self.addSaleContractAction.setText(_translate("MainWindow", "新建销售合同"))
        self.editCustomerAction.setText(_translate("MainWindow", "编辑客户"))
        self.editSaleContractAction.setText(_translate("MainWindow", "编辑销售合同"))
        self.getAvailableSerNrAction.setText(_translate("MainWindow", "获取出厂编号"))
        self.actionAdd2Contract.setText(_translate("MainWindow", "添加至合同"))
        self.actionAdd2Contract.setShortcut(_translate("MainWindow", "Ctrl+O"))
