# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PartMainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.operationMenu = QtWidgets.QMenu(self.menubar)
        self.operationMenu.setObjectName("operationMenu")
        self.dataMenu = QtWidgets.QMenu(self.menubar)
        self.dataMenu.setObjectName("dataMenu")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.tagDockWidget = QtWidgets.QDockWidget(MainWindow)
        self.tagDockWidget.setObjectName("tagDockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.tagDockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.tagDockWidget)
        self.partInfoDockWidget = QtWidgets.QDockWidget(MainWindow)
        self.partInfoDockWidget.setObjectName("partInfoDockWidget")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.partInfoDockWidget.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.partInfoDockWidget)
        self.partChildrenDockWidget = QtWidgets.QDockWidget(MainWindow)
        self.partChildrenDockWidget.setObjectName("partChildrenDockWidget")
        self.dockWidgetContents_3 = QtWidgets.QWidget()
        self.dockWidgetContents_3.setObjectName("dockWidgetContents_3")
        self.partChildrenDockWidget.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.partChildrenDockWidget)
        self.partParentDockWidget = QtWidgets.QDockWidget(MainWindow)
        self.partParentDockWidget.setObjectName("partParentDockWidget")
        self.dockWidgetContents_4 = QtWidgets.QWidget()
        self.dockWidgetContents_4.setObjectName("dockWidgetContents_4")
        self.partParentDockWidget.setWidget(self.dockWidgetContents_4)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.partParentDockWidget)
        self.purchaseDockWidget = QtWidgets.QDockWidget(MainWindow)
        self.purchaseDockWidget.setObjectName("purchaseDockWidget")
        self.dockWidgetContents_5 = QtWidgets.QWidget()
        self.dockWidgetContents_5.setObjectName("dockWidgetContents_5")
        self.purchaseDockWidget.setWidget(self.dockWidgetContents_5)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.purchaseDockWidget)
        self.partStructureDockWidget = QtWidgets.QDockWidget(MainWindow)
        self.partStructureDockWidget.setObjectName("partStructureDockWidget")
        self.dockWidgetContents_6 = QtWidgets.QWidget()
        self.dockWidgetContents_6.setObjectName("dockWidgetContents_6")
        self.partStructureDockWidget.setWidget(self.dockWidgetContents_6)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.partStructureDockWidget)
        self.exitMenuItem = QtWidgets.QAction(MainWindow)
        self.exitMenuItem.setObjectName("exitMenuItem")
        self.resetDocksMenuItem = QtWidgets.QAction(MainWindow)
        self.resetDocksMenuItem.setObjectName("resetDocksMenuItem")
        self.add2TreeViewMenuItem = QtWidgets.QAction(MainWindow)
        self.add2TreeViewMenuItem.setObjectName("add2TreeViewMenuItem")
        self.operationMenu.addAction(self.add2TreeViewMenuItem)
        self.operationMenu.addSeparator()
        self.operationMenu.addAction(self.exitMenuItem)
        self.menu.addAction(self.resetDocksMenuItem)
        self.menubar.addAction(self.operationMenu.menuAction())
        self.menubar.addAction(self.dataMenu.menuAction())
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "物料管理"))
        self.operationMenu.setTitle(_translate("MainWindow", "操作"))
        self.dataMenu.setTitle(_translate("MainWindow", "数据"))
        self.menu.setTitle(_translate("MainWindow", "窗体"))
        self.tagDockWidget.setWindowTitle(_translate("MainWindow", "标签"))
        self.partInfoDockWidget.setWindowTitle(_translate("MainWindow", "项目信息"))
        self.partChildrenDockWidget.setWindowTitle(_translate("MainWindow", "清单"))
        self.partParentDockWidget.setWindowTitle(_translate("MainWindow", "使用处"))
        self.purchaseDockWidget.setWindowTitle(_translate("MainWindow", "采购"))
        self.partStructureDockWidget.setWindowTitle(_translate("MainWindow", "产品结构"))
        self.exitMenuItem.setText(_translate("MainWindow", "关闭"))
        self.exitMenuItem.setToolTip(_translate("MainWindow", "退出程序"))
        self.exitMenuItem.setStatusTip(_translate("MainWindow", "退出程序。"))
        self.exitMenuItem.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.resetDocksMenuItem.setText(_translate("MainWindow", "重置布局"))
        self.add2TreeViewMenuItem.setText(_translate("MainWindow", "添加至树形视图"))

