# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PartMainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.operationMenu = QtWidgets.QMenu(self.menubar)
        self.operationMenu.setObjectName("operationMenu")
        self.dataMenu = QtWidgets.QMenu(self.menubar)
        self.dataMenu.setObjectName("dataMenu")
        self.menu = QtWidgets.QMenu(self.dataMenu)
        self.menu.setObjectName("menu")
        self.windowsMenu = QtWidgets.QMenu(self.menubar)
        self.windowsMenu.setObjectName("windowsMenu")
        self.settingMenu = QtWidgets.QMenu(self.menubar)
        self.settingMenu.setObjectName("settingMenu")
        self.tagMenu = QtWidgets.QMenu(self.menubar)
        self.tagMenu.setObjectName("tagMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.tagDockWidget = QtWidgets.QDockWidget(MainWindow)
        self.tagDockWidget.setObjectName("tagDockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.tagDockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.tagDockWidget)
        self.partInfoDockWidget = QtWidgets.QDockWidget(MainWindow)
        self.partInfoDockWidget.setObjectName("partInfoDockWidget")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.partInfoDockWidget.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.partInfoDockWidget)
        self.partChildrenDockWidget = QtWidgets.QDockWidget(MainWindow)
        self.partChildrenDockWidget.setObjectName("partChildrenDockWidget")
        self.dockWidgetContents_3 = QtWidgets.QWidget()
        self.dockWidgetContents_3.setObjectName("dockWidgetContents_3")
        self.partChildrenDockWidget.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.partChildrenDockWidget)
        self.partParentDockWidget = QtWidgets.QDockWidget(MainWindow)
        self.partParentDockWidget.setObjectName("partParentDockWidget")
        self.dockWidgetContents_4 = QtWidgets.QWidget()
        self.dockWidgetContents_4.setObjectName("dockWidgetContents_4")
        self.partParentDockWidget.setWidget(self.dockWidgetContents_4)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.partParentDockWidget)
        self.purchaseDockWidget = QtWidgets.QDockWidget(MainWindow)
        self.purchaseDockWidget.setObjectName("purchaseDockWidget")
        self.purchaseContents = QtWidgets.QWidget()
        self.purchaseContents.setObjectName("purchaseContents")
        self.purchaseDockWidget.setWidget(self.purchaseContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.purchaseDockWidget)
        self.partStructureDockWidget = QtWidgets.QDockWidget(MainWindow)
        self.partStructureDockWidget.setObjectName("partStructureDockWidget")
        self.dockWidgetContents_6 = QtWidgets.QWidget()
        self.dockWidgetContents_6.setObjectName("dockWidgetContents_6")
        self.partStructureDockWidget.setWidget(self.dockWidgetContents_6)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.partStructureDockWidget)
        self.exitMenuItem = QtWidgets.QAction(MainWindow)
        self.exitMenuItem.setObjectName("exitMenuItem")
        self.resetDocksMenuItem = QtWidgets.QAction(MainWindow)
        self.resetDocksMenuItem.setObjectName("resetDocksMenuItem")
        self.add2TreeViewMenuItem = QtWidgets.QAction(MainWindow)
        self.add2TreeViewMenuItem.setObjectName("add2TreeViewMenuItem")
        self.importPartListMenuItem = QtWidgets.QAction(MainWindow)
        self.importPartListMenuItem.setObjectName("importPartListMenuItem")
        self.exportPartListMenuItem = QtWidgets.QAction(MainWindow)
        self.exportPartListMenuItem.setObjectName("exportPartListMenuItem")
        self.columnViewMenuItem = QtWidgets.QAction(MainWindow)
        self.columnViewMenuItem.setObjectName("columnViewMenuItem")
        self.refreshMenuItem = QtWidgets.QAction(MainWindow)
        self.refreshMenuItem.setObjectName("refreshMenuItem")
        self.add2OutputListMenuItem = QtWidgets.QAction(MainWindow)
        self.add2OutputListMenuItem.setObjectName("add2OutputListMenuItem")
        self.showOutputListMenuItem = QtWidgets.QAction(MainWindow)
        self.showOutputListMenuItem.setObjectName("showOutputListMenuItem")
        self.tagEditModeMenuItem = QtWidgets.QAction(MainWindow)
        self.tagEditModeMenuItem.setCheckable(True)
        self.tagEditModeMenuItem.setObjectName("tagEditModeMenuItem")
        self.doTaggedMenuItem = QtWidgets.QAction(MainWindow)
        self.doTaggedMenuItem.setVisible(False)
        self.doTaggedMenuItem.setObjectName("doTaggedMenuItem")
        self.statisticsInTimeAction = QtWidgets.QAction(MainWindow)
        self.statisticsInTimeAction.setCheckable(True)
        self.statisticsInTimeAction.setObjectName("statisticsInTimeAction")
        self.allStatisticsAction = QtWidgets.QAction(MainWindow)
        self.allStatisticsAction.setCheckable(True)
        self.allStatisticsAction.setObjectName("allStatisticsAction")
        self.purchaseStatisticsAction = QtWidgets.QAction(MainWindow)
        self.purchaseStatisticsAction.setCheckable(True)
        self.purchaseStatisticsAction.setChecked(True)
        self.purchaseStatisticsAction.setObjectName("purchaseStatisticsAction")
        self.assemblyStatisticsAction = QtWidgets.QAction(MainWindow)
        self.assemblyStatisticsAction.setCheckable(True)
        self.assemblyStatisticsAction.setObjectName("assemblyStatisticsAction")
        self.selectDefaultTagMenuItem = QtWidgets.QAction(MainWindow)
        self.selectDefaultTagMenuItem.setObjectName("selectDefaultTagMenuItem")
        self.addTag2PartMenuItem = QtWidgets.QAction(MainWindow)
        self.addTag2PartMenuItem.setObjectName("addTag2PartMenuItem")
        self.showPriceAction = QtWidgets.QAction(MainWindow)
        self.showPriceAction.setCheckable(True)
        self.showPriceAction.setVisible(False)
        self.showPriceAction.setObjectName("showPriceAction")
        self.operationMenu.addSeparator()
        self.operationMenu.addAction(self.add2OutputListMenuItem)
        self.operationMenu.addAction(self.showOutputListMenuItem)
        self.operationMenu.addSeparator()
        self.operationMenu.addAction(self.exitMenuItem)
        self.menu.addAction(self.allStatisticsAction)
        self.menu.addAction(self.purchaseStatisticsAction)
        self.menu.addAction(self.assemblyStatisticsAction)
        self.dataMenu.addAction(self.refreshMenuItem)
        self.dataMenu.addSeparator()
        self.dataMenu.addAction(self.importPartListMenuItem)
        self.dataMenu.addAction(self.exportPartListMenuItem)
        self.dataMenu.addSeparator()
        self.dataMenu.addAction(self.add2TreeViewMenuItem)
        self.dataMenu.addAction(self.statisticsInTimeAction)
        self.dataMenu.addAction(self.menu.menuAction())
        self.dataMenu.addAction(self.showPriceAction)
        self.windowsMenu.addAction(self.resetDocksMenuItem)
        self.settingMenu.addAction(self.columnViewMenuItem)
        self.tagMenu.addAction(self.tagEditModeMenuItem)
        self.tagMenu.addAction(self.doTaggedMenuItem)
        self.tagMenu.addSeparator()
        self.tagMenu.addAction(self.selectDefaultTagMenuItem)
        self.tagMenu.addAction(self.addTag2PartMenuItem)
        self.menubar.addAction(self.operationMenu.menuAction())
        self.menubar.addAction(self.dataMenu.menuAction())
        self.menubar.addAction(self.tagMenu.menuAction())
        self.menubar.addAction(self.windowsMenu.menuAction())
        self.menubar.addAction(self.settingMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "物料管理"))
        self.operationMenu.setTitle(_translate("MainWindow", "操作"))
        self.dataMenu.setTitle(_translate("MainWindow", "列表"))
        self.menu.setTitle(_translate("MainWindow", "统计设置"))
        self.windowsMenu.setTitle(_translate("MainWindow", "窗体"))
        self.settingMenu.setTitle(_translate("MainWindow", "设置"))
        self.tagMenu.setTitle(_translate("MainWindow", "标签"))
        self.tagDockWidget.setWindowTitle(_translate("MainWindow", "标签"))
        self.partInfoDockWidget.setWindowTitle(_translate("MainWindow", "项目信息"))
        self.partChildrenDockWidget.setWindowTitle(_translate("MainWindow", "清单"))
        self.partParentDockWidget.setWindowTitle(_translate("MainWindow", "使用处"))
        self.purchaseDockWidget.setWindowTitle(_translate("MainWindow", "采购"))
        self.partStructureDockWidget.setWindowTitle(_translate("MainWindow", "产品结构"))
        self.exitMenuItem.setText(_translate("MainWindow", "关闭"))
        self.exitMenuItem.setToolTip(_translate("MainWindow", "退出程序"))
        self.exitMenuItem.setStatusTip(_translate("MainWindow", "退出程序。"))
        self.exitMenuItem.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.resetDocksMenuItem.setText(_translate("MainWindow", "重置布局"))
        self.add2TreeViewMenuItem.setText(_translate("MainWindow", "添加至树形视图"))
        self.importPartListMenuItem.setText(_translate("MainWindow", "导入项目列表"))
        self.exportPartListMenuItem.setText(_translate("MainWindow", "导出项目列表"))
        self.columnViewMenuItem.setText(_translate("MainWindow", "项目显示列设置"))
        self.refreshMenuItem.setText(_translate("MainWindow", "刷新"))
        self.refreshMenuItem.setShortcut(_translate("MainWindow", "F5"))
        self.add2OutputListMenuItem.setText(_translate("MainWindow", "添加至输出清单"))
        self.add2OutputListMenuItem.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.showOutputListMenuItem.setText(_translate("MainWindow", "输出清单"))
        self.tagEditModeMenuItem.setText(_translate("MainWindow", "编辑模式"))
        self.tagEditModeMenuItem.setStatusTip(_translate("MainWindow", "激活标签页的编辑功能。"))
        self.doTaggedMenuItem.setText(_translate("MainWindow", "打标签"))
        self.doTaggedMenuItem.setStatusTip(_translate("MainWindow", "为某项项目打上标签。"))
        self.doTaggedMenuItem.setShortcut(_translate("MainWindow", "F4"))
        self.statisticsInTimeAction.setText(_translate("MainWindow", "实时统计"))
        self.allStatisticsAction.setText(_translate("MainWindow", "完全"))
        self.purchaseStatisticsAction.setText(_translate("MainWindow", "投料"))
        self.assemblyStatisticsAction.setText(_translate("MainWindow", "装配"))
        self.selectDefaultTagMenuItem.setText(_translate("MainWindow", "设置默认标签组"))
        self.selectDefaultTagMenuItem.setIconText(_translate("MainWindow", "新创建标签时，默认加入该标签。"))
        self.selectDefaultTagMenuItem.setToolTip(_translate("MainWindow", "新创建标签时，默认加入该标签。"))
        self.addTag2PartMenuItem.setText(_translate("MainWindow", "添加标签"))
        self.addTag2PartMenuItem.setShortcut(_translate("MainWindow", "F3"))
        self.showPriceAction.setText(_translate("MainWindow", "显示价格"))

